# Generated by Django 5.1.7 on 2025-03-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crd_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchday',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Speedy Match', max_length=255),
            preserve_default=False,
        ),
    ]
